name: CI Pipeline

on:
  push:
    paths:
    - ".github/workflows/ci.yml"
    - "src/**"
    - "pom.xml"
    - "Dockerfile"
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:  
      MVN: mvn --show-version --batch-mode -Dbuild_version=${{ github.run_number }}
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache ~/.m2
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: Build
      run: ${MVN} clean compile
      
    - name: Test
      run: ${MVN} test
      
    - name: Package
      run: ${MVN} package
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: |
          target/vulnapp-${{ github.run_number }}.jar
          Dockerfile
  
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:  
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true
          
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: release
        path: /home/runner/work/gh-adv-sec/gh-adv-sec/
        
    - name: Build & Publish image
      uses: docker/build-push-action@v2
      with:
        build-args: build_number=${{ github.run_number }}
        push: true
        context: /home/runner/work/gh-adv-sec/gh-adv-sec
        tags: |
          docker.pkg.github.com/${{ github.repository }}/gh-adv-sec:${{ github.sha }}
          docker.pkg.github.com/${{ github.repository }}/gh-adv-sec:${{ github.run_number }}
