name: CI Pipeline

on:
  push:
    paths:
    - ".github/workflows/ci.yml"
    - "src/**"
    - "pom.xml"
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      MVN: mvn --show-version --batch-mode -Dbuild_version=${{ github.run_number }}
    steps:  
    - name: checkout
      uses: actions/checkout@v2
      
    - name: cache ~/.m2
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: build
      run: ${MVN} clean compile
      
    - name: test
      run: ${MVN} test
      
    - name: package
      if: github.ref == 'refs/heads/main'
      run: ${MVN} package -DskipTests
      
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-jar
        path: target/vulnapp-${{ github.run_number }}.jar
  
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:  
    - name: docker login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true
          
    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: app-jar
        path: app.jar
    
    - name: publish container image
      uses: docker/build-push-action@v2
      with:
        build-args: build_number=${{ github.run_number }}
        push: true
        tags: |
          docker.pkg.github.com/${{ github.repository }}/image:${{ github.sha }}
          docker.pkg.github.com/${{ github.repository }}/image:${{ github.run_number }}
