name: CI Pipeline

on:
  push:
    paths:
    - ".github/workflows/ci.yml"
    - "src/**"
    - "pom.xml"
  pull_request:
    branches: [ main ]

env:
  build_number: ${{ github.run_number }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      MVN: mvn --show-version --batch-mode -Dbuild_version=${build_number}
    steps:
    
    - name: checkout
      uses: actions/checkout@v2
      
    - name: cache ~/.m2
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: build
      run: ${MVN} clean compile
      
    - name: test
      run: ${MVN} test
      
    - name: package
      if: github.ref == 'refs/heads/master'
      run: ${MVN} package -DskipTests
      
    - name: docker login
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: build and release image
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          docker.pkg.github.com/${{ github.repository }}/image:${{ github.sha }}
          docker.pkg.github.com/${{ github.repository }}/image:${build_number}
