name: "Code Analysis"

on:
  push:
    paths:
      - "src/**"
      - "pom.xml"
    branches-ignore: [ 'dependabot/**' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '32 5 * * 2'

concurrency:
  group: sast-$${{ github.ref }}
  cancel-in-progress: true

jobs:

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
    - name: Print refs
      run: |
        echo ${{ github.ref }}

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: cache ~/.m2
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main

    - name: Build Application
      run: ${MVN} package -DskipTests

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
