name: "Code Analysis"

on:
  push:
    paths:
      - "src/**"
      - "pom.xml"
      - ".github/workflows/sast.yml"
    branches-ignore: [ 'dependabot/**' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '32 5 * * 2'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: cache ~/.m2
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        config-file: ubpass/gh-adv-sec-config/codeql-config.yaml@main
#        external-repository-token: ${{ secrets.GITHUB_TOKEN }}
        queries: ./.github/codeql

    - name: Build Application
      run: ${MVN} package -DskipTests

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
